language: php

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: deps=low
    - php: 7.2
    - php: 7.2
      env: deps=low
    - php: 7.3
    - php: 7.3
      env: deps=low
    - php: 7.4
    - php: 7.4
      env: deps=low
    - php: nightly
      env: deps=low
    - php: nightly
  allow_failures:
    - php: nightly

depth: 1

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
    - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; fi

script:
  - composer validate
  - composer update
  - composer grumphp

install:
    - travis_retry composer install

after_success:
  - phpenv config-rm xdebug.ini
  - composer scrutinizer
